language: ruby
branches:
  only:
    - travis
rvm: 2.5
env:
  - DB=pgsql
services:
  - postgresql
before_script:
  - psql -c "CREATE USER rss WITH PASSWORD '1234';" -U postgres
  - RAILS_ENV=test bundle exec rake db:setup
script: bundle
script: bundle exec rake db:migrate
script: RAILS_ENV=test bundle exec rake spec

